export const metaKeywords = [
  "JavaScript development",
  "Frontend development",
  "JavaScript frameworks",
  "Web development",
  "Client-side scripting",
  "JavaScript libraries",
  "Responsive web design",
  "Single-page applications (SPAs)",
  "Cross-platform development",
  "Modern web development",
  "Next.js development",
  "React development",
  "Next.js developer",
  "React developer",
  "Nigerian developer",
  "Graphic design",
  "Brand design",
  "UI/UX design",
  "SEO strategies",
  "APIs integration",
  "Performance optimization",
  "Debugging",
  "Collaboration",
  "Communication",
  "Version control (Git)",
  "Open source programming",
  "Problem-solving",
  "User engagement",
  "Inventory management system",
  "User authentication",
  "Customizable themes",
  "Media queries",
  "Typescript",
  "Google Workspace",
  "UI/UX principles",
  "Social media management",
  "Project management",
  "Jira",
  "Trello",
  "Presentation software",
  "Web analytics",
];
