import "@/styles/globals.css";
import type { AppProps } from "next/app";
import Head from "next/head";
import Aos from "aos";
import "aos/dist/aos.css";
import { useEffect } from "react";

export default function App({ Component, pageProps }: AppProps) {
  useEffect(() => {
    Aos.init({
      duration: 500,
      once: true,
    });
  }, []);

  return (
    <>
      <Head>
        <title>Michael Israel</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"
        />
        {/* <link rel="icon" href="/icon_favicon/favicon.ico" /> */}
      </Head>

      <Component {...pageProps} />
    </>
  );
}
